### ISSUE TITLE
Fixed times and color temperature

### ISSUE THREAD

**Issue by elias-mueller** [WinEunuuchs2Unix/eyesome#1]
It would be great if one could choose the exact time for sunset and sunrise.

Also, being able to set color temperature would be nice.

**Comment by WinEunuuchs2Unix** [comment]
Thank you for your suggestion. I have just started coding color temperature in range 1000K to 10,000K using gamma table from sct which took gamma settings from redshift. You can use your own sunrise and sunset time in the files /usr/local/bin/.eyesome-sunrise and /usr/local/bin/.eyesome-sunset.

**Comment by WinEunuuchs2Unix** [comment]
Color Temperature slider has been added today. You can manually set sunrise and sunset time with `sudo echo "7:00 am" > /usr/local/bin/.eyesome-sunrise` and `sudo echo "9:00 pm" > /usr/local/bin/.eyesome-sunset`. Then break the http link to your city name in the Edit Configuration function. Thank you for suggesting color temperature slider. It was a great idea.

**Comment by ieremies** [comment]
I can't seem to find where this temperature feature is.

**Comment by defensem3ch** [comment]
I can't find it either

**Comment by defensem3ch** [comment]
Ah, found it - need to use "Override"
