### ISSUE TITLE
xrandr error setting gama

### ISSUE THREAD

**Issue by ieremies** [WinEunuuchs2Unix/eyesome#4]
Hey, I just installed it in my Manjaro and when it tries to set gamma value it gives this error
```
/usr/local/bin/eyesome-src.sh: line 561: echo: write error: Invalid argument
xrandr: --gamma: invalid argument '1,00:1,00:1,00'
Try 'xrandr --help' for more information.
```

I suspect it is because the dot instead of a comma in the values, but i don't know enough bash to make a fix.

**Comment by WinEunuuchs2Unix** [comment]
This will take some research. [Techmint has a good article on locale](https://www.tecmint.com/set-system-locales-in-linux/). In a nutshell enter `locale` command to see your system setup:

    $ locale
    LANG=en_CA.UTF-8
    LANGUAGE=en_CA:en
    LC_CTYPE="en_CA.UTF-8"
    LC_NUMERIC="en_CA.UTF-8"

Your `LC_NUMERIC` is probably setup for French language or another like that which uses `,` for the decimal point separator instead of `.` like my system uses above.

I will need your help to test the correct `LC` commands to put in the bash script. In the meantime please review the link above to know how your system is setup.

**Comment by ieremies** [comment]
Yep, Brazilian here:

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
...
```

I will be happy to help.

**Comment by WinEunuuchs2Unix** [comment]
Thanks for helping test eyesome for international users. Try this to temporary override decimal separator for eyesome only and leave other packages unaffected:

    LC_NUMERIC=C
    sudo eyesome-cfg.sh

Then edit configuration and set monitors' daytime/nighttime brightness and gamma. Save the configuration and quit eyesome. Now check eyesome's configuration file:

$ cat /usr/local/bin/.eyesome-cfg
https://www.timeanddate.com/sun/canada/edmonton|59.000000|120.000000|90.000000|2.000000|TRUE| | | | |1|Enabled|Hardware|Alien 17" Builtin DIsplay|intel_backlight|eDP-1-1|3500.000000|1.000000|1.000000|1.000000|850.000000|1.000000|0.880000|0.760000|3500|1.000000:1.000000:1.000000| | | | |2|Enabled|Software|Sony 50" TV|xrandr|HDMI-0|1.000000|1.000000|1.000000|1.000000|0.750000|1.000000|0.920000|0.850000|1.00|1.000000:1.000000:1.000000| | | | |3|Enabled|Software|Toshibal 43" 4K TV|xrandr|DP-1-1|1.000000|1.000000|1.000000|1.000000|0.630000|1.000000|0.850000|0.710000|1.00|1.000000:1.000000:1.000000| | | | 

You should now see `1.000000` where `1,000000` used to be.

**Comment by ieremies** [comment]
Yes, it does work now. I've yet to confirm if at nighttime (and sunrise) it will work properly but using the tests it does work perfectly now.

**Comment by WinEunuuchs2Unix** [comment]
Thanks for letting me know! I've changed `/usr/local/bin/eyesome-src.sh` with a new line (after initial comments): `export LC_NUMERIC="C"` I will publish this on github in a couple of days (I have other changes for Sun Times I need to test). You can insert this line into your own version until the github is updated.

**Comment by ieremies** [comment]
So, sorry for the late feedback, but I just opened my laptop now (nighttime) and it did nothing, my full brightness was still on. Not sure if it is related to this issue, since journalctl only says:

```
jun 08 20:32:54 ieremies-pc eyesome[76461]: Wakeup: Called from suspend.
jun 08 20:32:54 ieremies-pc systemd-sleep[76461]: /usr/local/bin/wake-eyesome.sh: line 100: kill: 76301,76301)---(sd-executor)(76457,76301)-+-systemd-wake-ey(76459,76301)---wake-eyesome.sh(76461: arguments must be process or job IDs

```

**Comment by WinEunuuchs2Unix** [comment]
@leremies When you type `journalctl | grep eyesome` there should be more. Setting for nighttime depends on sunrise and sunset tipe. Use `cat /usr/local/bin/.eyesome-sun*` to see that. It also depends on your monitor being setup correctly. Is it enabled? Does it have the correct Internal Name (revealed with `cat /sys/class/backlight/`)? If we are talking about a monitor attached to a laptop then it needs the correct `xrandr --listmonitors` name and not a `backlight` name. Finally did you edit `/usr/local/bin/eyesome-src.sh` with the `export LC_NUMERIC="C"` line? If so you need to reboot your laptop for this to take effect as eyesome daemon (`/usr/local/bin/eyesome.sh`) is loaded at boot time and stays in memory until next reboot.

**Comment by WinEunuuchs2Unix** [comment]
@Ieremies Rather than waiting for sunrise or sunset you can test your monitor setup anytime by clicking the **Daytime** and **Nighttime** buttons on the main menu for a quick 5 second test. Then click the **Edit** button to change monitor setup to your liking.

**Comment by WinEunuuchs2Unix** [comment]
No response in two months. Assume OP's problem has been solved by following recommendations.
